/*--------------------------------------------------------------------------------------+
|
|     $Source: MSPython\MSPythonWrapper\PyDgnPlatform\source\PyDgnPlatform.cpp $
|
|  $Copyright: (c) 2023 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#include "MSPythonPCH.h"

/*---------------------------------------------------------------------------------**//**
* Forward declarations for class definition generators.
* @bsimethod                                                                       2/2023
+---------------+---------------+---------------+---------------+---------------+------*/
void def_ArcHandlers(py::module_&);
void def_AreaPattern(py::module_&);
void def_AssociativePoint(py::module_&);
void def_AssocRegionHandler(py::module_&);
void def_BRepCellHandler(py::module_&);
void def_BSplineCurveHandler(py::module_&);
void def_BSplineSurfaceHandler(py::module_&);
void def_CellHeaderHandler(py::module_&);
void def_ChainHeaderHandlers(py::module_&);
void def_ClipPrimitive(py::module_&);
void def_ClipVector(py::module_&);
void def_ColorBook(py::module_&);
void def_ComplexHeaderHandler(py::module_&);
void def_ConeHander(py::module_&);
void def_CurveHandler(py::module_&);
void def_CustomItemType(py::module_&);
void def_PickList(py::module_&);
void def_DependencyManager(py::module_&);
void def_DgnAttachment(py::module_&);
void def_DgnColorMap(py::module_&);
void def_DgnComponentHandlers(py::module_&);
void def_DgnCore(py::module_&);
void def_DgnDocumentManager(py::module_&);
void def_DgnECFinders(py::module_&);
void def_DgnHost(py::module_&);
void def_DgnECManager(py::module_&);
void def_DgnFile(py::module_&);
void def_DgnFontManager(py::module_&);
void def_DgnLinkHandler(py::module_&);
void def_DgnLinkManager(py::module_&);
void def_DgnLinks(py::module_&);
void def_DgnLinkTree(py::module_&);
void def_DgnModel(py::module_&);
void def_DgnModelRef(py::module_&);
void def_DgnPlatform(py::module_&);
void def_DgnPlatform_r(py::module_&);
void def_DgnPlatformBaseType_r(py::module_&);
void def_DgnPlatformErrors_r(py::module_&);
void def_DgnPlatformLib(py::module_&);
void def_DgnStoreHandlers(py::module_&);
void def_DgnTextSnippet(py::module_&);
void def_DgnTextStyle(py::module_&);
void def_DgnTextStyleProperties_r(py::module_&);
void def_DgnViewport(py::module_&);
void def_DigitalSignatureCellHeaderHandler(py::module_&);
void def_DimensionHandler(py::module_&);
void def_DimensionStyle(py::module_&);
void def_DimensionStyleProps_r(py::module_&);
void def_DisplayFilter(py::module_&);
void def_DisplayFilterManager(py::module_&);
void def_DisplayHandler(py::module_&);
void def_DisplayPath(py::module_&);
void def_DisplayRuleActions(py::module_&);
void def_DisplayRules(py::module_&);
void def_DisplayRulesManager(py::module_&);
void def_DisplayStyleManager(py::module_&);
void def_DropGraphics(py::module_&);
void def_ECInstanceHolderHandler(py::module_& m);
void def_ElementAgenda(py::module_&);
void def_ElementCopyContext(py::module_&);
void def_ElementGeometry(py::module_&);
void def_ElementGraphics(py::module_&);
void def_ElementHandle(py::module_&);
void def_ElementProperties(py::module_&);
void def_ElementTemplateParamsHelper(py::module_&);
void def_ElementTemplateUtils(py::module_&);
void def_ExtendedElementHandler(py::module_&);
void def_FenceParams(py::module_&);
void def_GPArray(py::module_&);
void def_GroupedHoleHandler(py::module_&);
void def_Handler(py::module_&);
void def_HitPath(py::module_&);
void def_HttpHandler(py::module_&);
void def_HUDMarker(py::module_&);
void def_IAnnotationHandler(py::module_&);
void def_IAreaFillProperties(py::module_&);
void def_IAuxCoordSys(py::module_&);
void def_IconElementHandler(py::module_&);
void def_image(py::module_&);
void def_IMaterialProperties(py::module_&);
void def_INamedViewElementHandler(py::module_&);
void def_IPointCloud(py::module_&);
void def_IRasterAttachment(py::module_&);
void def_IRasterSourceFileQuery(py::module_&);
void def_ISettings(py::module_&);
void def_ISprite(py::module_&);
void def_ITextEdit(py::module_&);
void def_ITransactionHandler(py::module_&);
void def_ITxnManager(py::module_&);
void def_IViewDraw(py::module_&);
void def_IViewOutput(py::module_&);
void def_IViewTransients(py::module_&);
void def_IXDataNodeHandler(py::module_&);
void def_LevelCache(py::module_&);
void def_LevelTypes(py::module_&);
void def_Light(py::module_&);
void def_LinearHandlers(py::module_&);
void def_LineStyle(py::module_&);
void def_LineStyleManager(py::module_&);
void def_Locate(py::module_&);
void def_lstyle(py::module_&);
void def_Material(py::module_&);
void def_MaterialSettings(py::module_&);
void def_MeshHeaderHandler(py::module_&);
void def_ModelAccess(py::module_&);
void def_MultilineHandler(py::module_&);
void def_MultilineStyle(py::module_&);
void def_NamedBoundary(py::module_&);
void def_NamedGroup(py::module_&);
void def_NamedView(py::module_&);
void def_NoteHandler(py::module_&);
void def_NotificationManager(py::module_&);
void def_OleCellHeaderHandler(py::module_&);
void def_ParametricCellHandlers(py::module_&);
void def_ParametricModeling(py::module_&);
void def_PersistentElementPath(py::module_&);
void def_PersistentSnapPath(py::module_&);
void def_PointCloudClipHandler(py::module_&);
void def_PointCloudEdit(py::module_&);
void def_PointCloudHandler(py::module_&);
void def_PropertyContext(py::module_&);
void def_RasterAttachmentOverride(py::module_&);
void def_DgnRaster(py::module_& m);
void def_RasterHandlers(py::module_&);
void def_RasterCollection(py::module_&);
void def_RegionLinkProcessor(py::module_&);
void def_RegionUtil(py::module_&);
void def_RegisteredApp(py::module_&);
void def_RunPropertiesBase(py::module_&);
void def_SectionClip(py::module_&);
void def_SharedCellHandler(py::module_&);
void def_SolidKernel(py::module_&);
void def_StoredExpression(py::module_&);
void def_SurfaceAndSolidHandlers(py::module_&);
void def_SymbologyReporter(py::module_&);
void def_TagElementData(py::module_&);
void def_TagElementHandler(py::module_&);
void def_TemplateRefHandler(py::module_&);
void def_TemplateSymbologyRemapper(py::module_&);
void def_TextHandlers(py::module_&);
void def_TextParam(py::module_&);
void def_TextString(py::module_&);
void def_TextStringProperties(py::module_&);
void def_TextTableHandler(py::module_&);
void def_TransformClipStack(py::module_&);
void def_ValueFormat(py::module_&);
void def_ValueParse(py::module_&);
void def_ViewContext(py::module_&);
void def_ViewGroup(py::module_&);
void def_ViewInfo(py::module_&);
void def_WorkSet(py::module_&);
void def_XAttributeChange(py::module_&);
void def_XDataNodeCollection(py::module_&);
void def_XDataTreeManager(py::module_&);
void def_XDataTreeOwner(py::module_&);

void def_BentleyDgn(py::module_&);
void def_DgnAppData(py::module_&);
void def_DgnHistory(py::module_&);
void def_DgnItemIndex(py::module_&);
void def_DgnModelRefCollections(py::module_&);
void def_ElementRefBase(py::module_&);
void def_ModelInfo(py::module_&);
void def_MSElementDescr(py::module_&);
void def_ScaleDefinition(py::module_&);
void def_SheetDef(py::module_&);
void def_SheetSizeDefinition(py::module_&);
void def_UnitDefinition(py::module_&);
void def_XAttributeIter(py::module_&);
void def_DgnElements(py::module_&);

void def_Caret(py::module_&);
void def_CharStream(py::module_&);
void def_Fraction(py::module_&);
void def_IDgnTextStyleApplyable(py::module_&);
void def_Indentation(py::module_&);
void def_Paragraph(py::module_&);
void def_Run(py::module_&);
void def_RunProperties(py::module_&);
void def_TextAPICommon(py::module_&);
void def_TextBlock(py::module_&);
void def_TextBlockIterators(py::module_&);
void def_TextBlockSerialization(py::module_&);
void def_TextField(py::module_&);
void def_WhiteSpace(py::module_&);

void def_BitMask(py::module_&);
void def_ConfigurationManager(py::module_&);
void def_CsvFile(py::module_&);
void def_DependencyManagerLinkage(py::module_&);

void def_XmlFragment(py::module_&);
void def_QvViewport(py::module_&);

void def_BaseGCS(py::module_& m);
void def_DgnGCS(py::module_& m);

void def_DesignHistory(py::module_& m);

void def_BeTextFile(py::module_& m);
void def_Dsig(py::module_& m);
void def_DoubleValueFormat(py::module_& m);

void def_DgnECChangeManager (py::module_& m);

void def_IViewManager(py::module_& m);

/*---------------------------------------------------------------------------------**//**
* Module definition.
* @bsimethod                                                                       2/2023
+---------------+---------------+---------------+---------------+---------------+------*/
PYBIND11_MODULE(MSPyDgnPlatform, m)
    {
    // Document for module
    m.doc() = "The MSPyDgnPlatform library, is used to read and write DgnFiles. A design file is composed of Design Models. A model contains Elements. Use the Transaction Manager in order to persist changes";

    //From pybentley
    def_BeTextFile(m);
    def_Dsig(m);
    def_DoubleValueFormat(m);

    // class defines
    def_DgnPlatform(m);
    def_DgnPlatform_r(m);
    def_DgnAppData(m);
    def_BentleyDgn(m);
    def_BitMask(m);
    def_ConfigurationManager(m);
    def_CsvFile(m);
    def_Handler(m);
    def_DisplayHandler(m);
    def_IAreaFillProperties(m);
    def_ElementGeometry(m);
    def_ArcHandlers(m);
    def_AreaPattern(m);
    def_AssociativePoint(m);
    def_ITransactionHandler(m);
    def_ComplexHeaderHandler(m);
    def_IViewDraw(m);
    def_IAnnotationHandler(m);
    def_CellHeaderHandler(m);
    def_DependencyManagerLinkage(m);
    def_AssocRegionHandler(m);
    def_SolidKernel(m);
    def_BRepCellHandler(m);
    def_BSplineCurveHandler(m);
    def_BSplineSurfaceHandler(m);
    def_ChainHeaderHandlers(m);
    def_ClipPrimitive(m);
    def_ClipVector(m);
    def_ColorBook(m);    
    def_ConeHander(m);
    def_CurveHandler(m);
    def_CustomItemType(m);    
    def_PickList(m);
    def_DependencyManager(m);        
    def_DgnColorMap(m);
    def_DgnComponentHandlers(m);
    def_DgnCore(m);
    def_DgnDocumentManager(m);
    def_DgnECFinders(m);
    def_DgnHost(m);
	def_DgnECManager(m); 
    def_DgnFile(m);
    def_DgnFontManager(m);
    def_DgnLinkHandler(m);
    def_DgnLinkManager(m);
    def_DgnLinks(m);
    def_DgnLinkTree(m);
    def_ElementRefBase(m);
    def_DgnModelRef(m);
    def_DgnAttachment(m);
    def_DgnModel(m);    
    def_DgnPlatformBaseType_r(m);
    def_DgnPlatformErrors_r(m);
    def_DgnPlatformLib(m);
    def_DgnStoreHandlers(m);
    def_DgnTextSnippet(m);
    def_DgnTextStyle(m);
    def_DgnTextStyleProperties_r(m);
    def_DgnViewport(m);
    def_ITextEdit(m);
    def_XAttributeIter(m);
    def_ElementHandle(m);
    def_ElementAgenda(m);    
    def_DigitalSignatureCellHeaderHandler(m);
    def_DimensionHandler(m);
    def_DimensionStyle(m);
    def_DimensionStyleProps_r(m);    
    def_DisplayFilter(m);
    def_DisplayFilterManager(m);    
    def_DisplayPath(m);
    def_DisplayRuleActions(m);
    def_DisplayRules(m);
    def_DisplayRulesManager(m);    
    def_DisplayStyleManager(m);
    def_IViewOutput(m);
    def_DropGraphics(m);
    def_ECInstanceHolderHandler(m);
    def_ElementCopyContext(m);    
    def_ElementGraphics(m);    
    def_ITxnManager(m);
    def_ElementProperties(m);
    def_ElementTemplateParamsHelper(m);
    def_ElementTemplateUtils(m);
    def_ExtendedElementHandler(m);
    def_FenceParams(m);
    def_GPArray(m);
    def_GroupedHoleHandler(m);    
    def_HitPath(m);
    def_HttpHandler(m);
    def_HUDMarker(m);    
    def_IAuxCoordSys(m);
    def_IconElementHandler(m);
    def_image(m);
    def_IMaterialProperties(m);
    def_INamedViewElementHandler(m);
    def_IPointCloud(m);
    def_IRasterAttachment(m);
    def_IRasterSourceFileQuery(m);
    def_ISettings(m);
    def_ISprite(m);        
    def_IXDataNodeHandler(m);
    def_LevelCache(m);
    def_LevelTypes(m);
    def_Light(m);
    def_LinearHandlers(m);    
    def_LineStyleManager(m);
    def_Locate(m);
    def_lstyle(m);
    def_Material(m);
    def_MaterialSettings(m);
    def_MeshHeaderHandler(m);
    def_ModelAccess(m);
    def_MultilineHandler(m);
    def_MultilineStyle(m);
    def_NamedBoundary(m);
    def_NamedGroup(m);
    def_NamedView(m);
    def_NoteHandler(m);
    def_NotificationManager(m);    
    def_OleCellHeaderHandler(m);
    def_ParametricModeling(m);
    def_ParametricCellHandlers(m);    
    def_PersistentElementPath(m);
    def_PersistentSnapPath(m);
    def_PointCloudClipHandler(m);
    def_PointCloudEdit(m);
    def_PointCloudHandler(m);
    def_PropertyContext(m);
    def_RasterAttachmentOverride(m);
    def_DgnRaster(m);
    def_RasterHandlers(m);
    def_RasterCollection(m);
    def_RegionLinkProcessor(m);    
    def_RegisteredApp(m);
    def_RunPropertiesBase(m);
    def_SectionClip(m);
    def_SharedCellHandler(m);
    def_StoredExpression(m);
    def_SurfaceAndSolidHandlers(m);
    def_SymbologyReporter(m);
    def_TagElementData(m);
    def_TagElementHandler(m);
    def_TemplateRefHandler(m);
    def_TemplateSymbologyRemapper(m);
    def_TextHandlers(m);
    def_TextParam(m);
    def_TextString(m);
    def_TextStringProperties(m);
    def_TextTableHandler(m);
    def_TransformClipStack(m);
    def_ValueFormat(m);
    def_ValueParse(m);
    def_ViewContext(m);
    def_RegionUtil(m);
    def_LineStyle(m);
    def_ViewGroup(m);
    def_ViewInfo(m);    
    def_WorkSet(m);
    def_XAttributeChange(m);    
    def_XDataNodeCollection(m);
    def_XDataTreeManager(m);    
    def_XDataTreeOwner(m);    
    def_DgnHistory(m);
    def_DgnItemIndex(m);
    def_DgnModelRefCollections(m);    
    def_ModelInfo(m);
    def_DgnElements(m);
    def_MSElementDescr(m);
    def_ScaleDefinition(m);
    def_SheetDef(m);
    def_SheetSizeDefinition(m);
    def_UnitDefinition(m);
    def_Caret(m);
    def_Run(m);
    def_CharStream(m);
    def_Fraction(m);
    def_IDgnTextStyleApplyable(m);
    def_Indentation(m);
    def_Paragraph(m);    
    def_RunProperties(m);
    def_TextAPICommon(m);
    def_TextBlock(m);
    def_TextBlockIterators(m);
    def_TextBlockSerialization(m);
    def_TextField(m);
    def_WhiteSpace(m);    
    def_IViewTransients(m);
    def_XmlFragment(m);
    def_QvViewport(m);
    def_BaseGCS(m);
    def_DgnGCS(m);
    def_DesignHistory(m);
    def_DgnECChangeManager (m);

	//From DgnView
    def_IViewManager(m);
    }


