
/*--------------------------------------------------------------------------------------+
|
|     $Source: MSPython\MSPythonWrapper\PyMstnPlatform\source\MstnDefs.cpp $
|
|  $Copyright: (c) 2023 Bentley Systems, Incorporated. All rights reserved. $
|
+--------------------------------------------------------------------------------------*/
#include "MSPythonPCH.h"
#include <Mstn/MstnDefs.h>

/*---------------------------------------------------------------------------------**//**
* @bsimethod                                                                       6/2024
+---------------+---------------+---------------+---------------+---------------+------*/
void def_MstnDefs(py::module_& m)
    {
    m.attr("eMAX_LOCATE_PATH_DESCRIPTION") = (int)MAX_LOCATE_PATH_DESCRIPTION;
    m.attr("eMAX_FONTS") = (int)MAX_FONTS;
    m.attr("eMAX_POINTSTACKSIZE") = (int)MAX_POINTSTACKSIZE;
    m.attr("eMIN_ELEMDATA_SCANBUF_SIZE") = (int)MIN_ELEMDATA_SCANBUF_SIZE;
    m.attr("eMAX_PHYSSCREEN") = (int)MAX_PHYSSCREEN;
    m.attr("eMAX_DOCKREGIONS") = (int)MAX_DOCKREGIONS;
    m.attr("eMAXKEYINPROMPT") = (int)MAXKEYINPROMPT;
    m.attr("eMAX_LINEWEIGHTS") = (int)MAX_LINEWEIGHTS;
    m.attr("eMAX_LINESTYLES") = (int)MAX_LINESTYLES;
    m.attr("eMAX_DOWNUP_PER_LINESTYLE") = (int)MAX_DOWNUP_PER_LINESTYLE;
    m.attr("eMAX_FONT_NAME_BYTES") = (int)MAX_FONT_NAME_BYTES;
    m.attr("eMAX_FONT_NAME_LENGTH") = (int)MAX_FONT_NAME_LENGTH;
    m.attr("eMAX_COMMAND_CHARS") = (int)MAX_COMMAND_CHARS;
    m.attr("eMAX_COMMAND_BYTES") = (int)MAX_COMMAND_BYTES;
    m.attr("eMAX_KmlNodeChars") = (int)MAX_KmlNodeChars;
    m.attr("eMAX_TASKNAVIGATION_PATH_LENGTH") = (int)MAX_TASKNAVIGATION_PATH_LENGTH;
    m.attr("eMAX_UNPARSED_LENGTH") = (int)MAX_UNPARSED_LENGTH;
    m.attr("eMAX_UNPARSED_BYTES") = (int)MAX_UNPARSED_BYTES;
    m.attr("eLEVEL_NAME_LINKAGE") = (int)LEVEL_NAME_LINKAGE;
    m.attr("eLEVEL_DESCRIPTION_LINKAGE") = (int)LEVEL_DESCRIPTION_LINKAGE;
    m.attr("eMAX_FILTER_TABLE_NAME_LENGTH") = (int)MAX_FILTER_TABLE_NAME_LENGTH;
    m.attr("eMAX_FILTER_TABLE_NAME_BYTES") = (int)MAX_FILTER_TABLE_NAME_BYTES;
    m.attr("eMAX_FILTER_NAME_LENGTH") = (int)MAX_FILTER_NAME_LENGTH;
    m.attr("eMAX_FILTER_NAME_BYTES") = (int)MAX_FILTER_NAME_BYTES;
    m.attr("eMAX_FILTER_DESCRIPTION_LENGTH") = (int)MAX_FILTER_DESCRIPTION_LENGTH;
    m.attr("eMAX_FILTER_DESCRIPTION_BYTES") = (int)MAX_FILTER_DESCRIPTION_BYTES;
    m.attr("eMAX_FILTER_MEMBER_NAME_LENGTH") = (int)MAX_FILTER_MEMBER_NAME_LENGTH;
    m.attr("eMAX_FILTER_MEMBER_NAME_BYTES") = (int)MAX_FILTER_MEMBER_NAME_BYTES;
    m.attr("eMAX_FILTER_EXPRESSION_LENGTH") = (int)MAX_FILTER_EXPRESSION_LENGTH;
    m.attr("eMAX_FILTER_EXPRESSION_BYTES") = (int)MAX_FILTER_EXPRESSION_BYTES;
    m.attr("eMAX_FILTER_LIBRARY_NAME_LENGTH") = (int)MAX_FILTER_LIBRARY_NAME_LENGTH;
    m.attr("eMAX_FILTER_LIBRARY_NAME_BYTES") = (int)MAX_FILTER_LIBRARY_NAME_BYTES;
    m.attr("eTRANSIENT_FLAG_SNAPPABLE") = (int)TRANSIENT_FLAG_SNAPPABLE;
    m.attr("eTRANSIENT_FLAG_DISPLAYFIRST") = (int)TRANSIENT_FLAG_DISPLAYFIRST;
    m.attr("eTRANSIENT_FLAG_DONTINCLUDEINFIT") = (int)TRANSIENT_FLAG_DONTINCLUDEINFIT;
    m.attr("eTRANSIENT_FLAG_VIEWMASKFROMMODELREF") = (int)TRANSIENT_FLAG_VIEWMASKFROMMODELREF;
    m.attr("eTRANSIENT_FLAG_INCLUDEINPLOT") = (int)TRANSIENT_FLAG_INCLUDEINPLOT;
    m.attr("eTRANSIENT_FLAG_OVERLAY") = (int)TRANSIENT_FLAG_OVERLAY;
    m.attr("eTASK_ID_SIZE") = (int)TASK_ID_SIZE;
    m.attr("eBUILDSTRINGTOKENFLAG_ProhibitUTF8") = (int)BUILDSTRINGTOKENFLAG_ProhibitUTF8;
    m.attr("eFILL_NONE") = (int)FILL_NONE;
    m.attr("eFILL_OPAQUE") = (int)FILL_OPAQUE;
    m.attr("eFILL_OUTLINED") = (int)FILL_OUTLINED;
    m.attr("ePLOTSTYLE_BYLEVEL") = (int)PLOTSTYLE_BYLEVEL;
    m.attr("ePLOTSTYLE_BYCELL") = (int)PLOTSTYLE_BYCELL;
    m.attr("eDEFAULT_ByCellColor") = (int)DEFAULT_ByCellColor;
    m.attr("eDEFAULT_ByCellWeight") = (int)DEFAULT_ByCellWeight;
    m.attr("eDEFAULT_ByCellStyle") = (int)DEFAULT_ByCellStyle;
    m.attr("eFFILTER_READONLY") = (int)FFILTER_READONLY;
    m.attr("eFFILTER_SUBDIR") = (int)FFILTER_SUBDIR;
    m.attr("eLOCATE_Header") = (int)LOCATE_Header;
    m.attr("eLOCATE_Component") = (int)LOCATE_Component;
    m.attr("eLOCATE_NestCell") = (int)LOCATE_NestCell;
    m.attr("eLOCATE_NoCellHeader") = (int)LOCATE_NoCellHeader;
    m.attr("eVIEW_INLOCALCOORDS") = (int)VIEW_INLOCALCOORDS;
    m.attr("eVIEW_INGLOBALCOORDS") = (int)VIEW_INGLOBALCOORDS;
    m.attr("eCOORDFMT_SHORT") = (int)COORDFMT_SHORT;
    m.attr("eCOORDFMT_LONG") = (int)COORDFMT_LONG;
    m.attr("eCOORDFMT_DOUBLE") = (int)COORDFMT_DOUBLE;
    m.attr("eBACKGROUND_COLOR_VIEW") = (int)BACKGROUND_COLOR_VIEW;
    m.attr("eBACKGROUND_COLOR_DIALOG") = (int)BACKGROUND_COLOR_DIALOG;
    m.attr("eWINDOWGETSTATE_MINIMIZED") = (int)WINDOWGETSTATE_MINIMIZED;
    m.attr("eWINDOWGETSTATE_MAXIMIZED") = (int)WINDOWGETSTATE_MAXIMIZED;
    m.attr("eWINDOWGETSTATE_ICONIFIED") = (int)WINDOWGETSTATE_ICONIFIED;
    m.attr("eFONTNAMELISTMODEL_SortByName") = (int)FONTNAMELISTMODEL_SortByName;
    m.attr("eSECURITY_LEVEL_HIGH") = (int)SECURITY_LEVEL_HIGH;
    m.attr("eSECURITY_LEVEL_MEDIUM") = (int)SECURITY_LEVEL_MEDIUM;
    m.attr("eSECURITY_LEVEL_LOW") = (int)SECURITY_LEVEL_LOW;
    m.attr("eSECURITY_LEVEL_NONE") = (int)SECURITY_LEVEL_NONE;
    m.attr("eFORMAT_UNICODE") = (int)FORMAT_UNICODE;
    m.attr("eFORMAT_MULTIBYTE") = (int)FORMAT_MULTIBYTE;
    m.attr("eWINUPD_ALLPARTS") = (int)WINUPD_ALLPARTS;
    m.attr("eWINUPD_BORDERS") = (int)WINUPD_BORDERS;
    m.attr("eWINUPD_NONVIEWCONTENTS") = (int)WINUPD_NONVIEWCONTENTS;
    m.attr("eHANDLETYPE_HWND") = (int)HANDLETYPE_HWND;
    m.attr("eHANDLETYPE_HDC") = (int)HANDLETYPE_HDC;
    m.attr("eHANDLETYPE_BSHDC") = (int)HANDLETYPE_BSHDC;
    m.attr("eHANDLETYPE_BSHBITMAP") = (int)HANDLETYPE_BSHBITMAP;
    m.attr("eINVISGEOM_BYELEMENT") = (int)INVISGEOM_BYELEMENT;
    m.attr("eINVISGEOM_ALWAYS") = (int)INVISGEOM_ALWAYS;
    m.attr("eINVISGEOM_NEVER") = (int)INVISGEOM_NEVER;
    m.attr("eBUTTONTRANS_UP") = (int)BUTTONTRANS_UP;
    m.attr("eBUTTONTRANS_DOWN") = (int)BUTTONTRANS_DOWN;
    m.attr("eBUTTONTRANS_TIMEOUT") = (int)BUTTONTRANS_TIMEOUT;
    m.attr("eBUTTONTRANS_MOTION") = (int)BUTTONTRANS_MOTION;
    m.attr("eBUTTONTRANS_CLICK") = (int)BUTTONTRANS_CLICK;
    m.attr("eBUTTONTRANS_STARTDRAG") = (int)BUTTONTRANS_STARTDRAG;
    m.attr("eCORNER_UPPERLEFT") = (int)CORNER_UPPERLEFT;
    m.attr("eCORNER_LOWERLEFT") = (int)CORNER_LOWERLEFT;
    m.attr("eCORNER_LOWERRIGHT") = (int)CORNER_LOWERRIGHT;
    m.attr("eCORNER_UPPERRIGHT") = (int)CORNER_UPPERRIGHT;
    m.attr("eCORNER_ALL") = (int)CORNER_ALL;
    m.attr("eCORNER_ALL_RESIZED") = (int)CORNER_ALL_RESIZED;
    m.attr("eACS_RECTANGULAR") = (int)ACS_RECTANGULAR;
    m.attr("eACS_CYLINDRICAL") = (int)ACS_CYLINDRICAL;
    m.attr("eACS_SPHERICAL") = (int)ACS_SPHERICAL;
    m.attr("eFIXEDDEPTH") = (int)FIXEDDEPTH;
    m.attr("eELEMHIGH") = (int)ELEMHIGH;
    m.attr("eELEMLOW") = (int)ELEMLOW;
    m.attr("ePRESERVEZRANGE_USELOW") = (int)PRESERVEZRANGE_USELOW;
    m.attr("ePRESERVEZRANGE_USEHIGH") = (int)PRESERVEZRANGE_USEHIGH;
    
    //===================================================================================
    // enum class ButtonTrans
    py::enum_<ButtonTrans>(m, "ButtonTrans")
      .value("eUp", ButtonTrans::Up)
      .value("eDown", ButtonTrans::Down)
      .value("eTimeout", ButtonTrans::Timeout)
      .value("eMotion", ButtonTrans::Motion)
      .value("eClick", ButtonTrans::Click)
      .value("eStartDrag", ButtonTrans::StartDrag)
      .value("eUndefined", ButtonTrans::Undefined)
      .export_values();
    
    //===================================================================================
    // enum class MdlApplicationClass
    py::enum_<MdlApplicationClass>(m, "MdlApplicationClass")
      .value("eNoChange", MdlApplicationClass::NoChange)
      .value("eUser", MdlApplicationClass::User)
      .value("eMSRequired", MdlApplicationClass::MSRequired)
      .value("eInitApp", MdlApplicationClass::InitApp)
      .value("eDGNApp", MdlApplicationClass::DGNApp)
      .value("eUIServer", MdlApplicationClass::UIServer)
      .value("ePlotDriver", MdlApplicationClass::PlotDriver)
      .value("eAutoDGN", MdlApplicationClass::AutoDGN)
      .value("eStayResidentServer", MdlApplicationClass::StayResidentServer)
      .value("eManaged", MdlApplicationClass::Managed)
      .value("eLicenseApp", MdlApplicationClass::LicenseApp)
      .value("eRibbonProvider", MdlApplicationClass::RibbonProvider)
      .export_values();

    //===================================================================================
    // enum class Workmode
    py::enum_<Workmode>(m, "Workmode")
      .value("eWORKMODE_DGN", Workmode::WORKMODE_DGN)
      .value("eWORKMODE_DWG", Workmode::WORKMODE_DWG)
      .value("eWORKMODE_V7", Workmode::WORKMODE_V7)
      .export_values();
    
    //===================================================================================
    // enum class IconStyle
    py::enum_<IconStyle>(m, "IconStyle")
      .value("eICON_STYLE_NORMAL", IconStyle::ICON_STYLE_NORMAL)
      .value("eICON_STYLE_LGREY", IconStyle::ICON_STYLE_LGREY)
      .value("eICON_STYLE_DGREY", IconStyle::ICON_STYLE_DGREY)
      .value("eICON_STYLE_DISABLED", IconStyle::ICON_STYLE_DISABLED)
      .value("eICON_STYLE_HIGHLIGHT", IconStyle::ICON_STYLE_HIGHLIGHT)
      .export_values();
    
    //===================================================================================
    // enum class SysColor
    py::enum_<SysColor>(m, "SysColor")
      .value("eSYSCOLOR_FIXED_BASE", SysColor::SYSCOLOR_FIXED_BASE)
      .value("eSYSCOLOR_FIXED_BLACK", SysColor::SYSCOLOR_FIXED_BLACK)
      .value("eSYSCOLOR_FIXED_BLUE", SysColor::SYSCOLOR_FIXED_BLUE)
      .value("eSYSCOLOR_FIXED_GREEN", SysColor::SYSCOLOR_FIXED_GREEN)
      .value("eSYSCOLOR_FIXED_CYAN", SysColor::SYSCOLOR_FIXED_CYAN)
      .value("eSYSCOLOR_FIXED_RED", SysColor::SYSCOLOR_FIXED_RED)
      .value("eSYSCOLOR_FIXED_MAGENTA", SysColor::SYSCOLOR_FIXED_MAGENTA)
      .value("eSYSCOLOR_FIXED_YELLOW", SysColor::SYSCOLOR_FIXED_YELLOW)
      .value("eSYSCOLOR_FIXED_WHITE", SysColor::SYSCOLOR_FIXED_WHITE)
      .value("eSYSCOLOR_FIXED_LGREY", SysColor::SYSCOLOR_FIXED_LGREY)
      .value("eSYSCOLOR_FIXED_DGREY", SysColor::SYSCOLOR_FIXED_DGREY)
      .value("eSYSCOLOR_FIXED_MGREY", SysColor::SYSCOLOR_FIXED_MGREY)
      .value("eSYSCOLOR_FIXED_PSEUDOWHITE", SysColor::SYSCOLOR_FIXED_PSEUDOWHITE)
      .value("eSYSCOLOR_FIXED_DARKBLUE", SysColor::SYSCOLOR_FIXED_DARKBLUE)
      .value("eSYSCOLOR_FIXED_TURQUOISE", SysColor::SYSCOLOR_FIXED_TURQUOISE)
      .value("eSYSCOLOR_FIXED_DARKGREEN", SysColor::SYSCOLOR_FIXED_DARKGREEN)
      .value("eSYSCOLOR_FIXED_MAROON", SysColor::SYSCOLOR_FIXED_MAROON)
      .value("eSYSCOLOR_FIXED_VIOLET", SysColor::SYSCOLOR_FIXED_VIOLET)
      .value("eSYSCOLOR_FIXED_DARKYELLOW", SysColor::SYSCOLOR_FIXED_DARKYELLOW)
      .value("eSYSCOLOR_BACKGROUND_PALEYELLOW", SysColor::SYSCOLOR_BACKGROUND_PALEYELLOW)
      .value("eSYSCOLOR_FIXED_MAXCOLORS", SysColor::SYSCOLOR_FIXED_MAXCOLORS)
      .value("eSYSCOLOR_WINDOWS_BASE", SysColor::SYSCOLOR_WINDOWS_BASE)
      .value("eSYSCOLOR_WINDOWS_WINBACKGROUND", SysColor::SYSCOLOR_WINDOWS_WINBACKGROUND)
      .value("eSYSCOLOR_WINDOWS_WINTEXT", SysColor::SYSCOLOR_WINDOWS_WINTEXT)
      .value("eSYSCOLOR_WINDOWS_MENU", SysColor::SYSCOLOR_WINDOWS_MENU)
      .value("eSYSCOLOR_WINDOWS_MENUTEXT", SysColor::SYSCOLOR_WINDOWS_MENUTEXT)
      .value("eSYSCOLOR_WINDOWS_SCROLLBAR", SysColor::SYSCOLOR_WINDOWS_SCROLLBAR)
      .value("eSYSCOLOR_WINDOWS_BTNFACE", SysColor::SYSCOLOR_WINDOWS_BTNFACE)
      .value("eSYSCOLOR_WINDOWS_BTNSHADOW", SysColor::SYSCOLOR_WINDOWS_BTNSHADOW)
      .value("eSYSCOLOR_WINDOWS_BTNTEXT", SysColor::SYSCOLOR_WINDOWS_BTNTEXT)
      .value("eSYSCOLOR_WINDOWS_BTNHIGHLIGHT", SysColor::SYSCOLOR_WINDOWS_BTNHIGHLIGHT)
      .value("eSYSCOLOR_WINDOWS_GRAYTEXT", SysColor::SYSCOLOR_WINDOWS_GRAYTEXT)
      .value("eSYSCOLOR_WINDOWS_HIGHLIGHT", SysColor::SYSCOLOR_WINDOWS_HIGHLIGHT)
      .value("eSYSCOLOR_WINDOWS_HIGHLIGHTTEXT", SysColor::SYSCOLOR_WINDOWS_HIGHLIGHTTEXT)
      .value("eSYSCOLOR_WINDOWS_WINFRAME", SysColor::SYSCOLOR_WINDOWS_WINFRAME)
      .value("eSYSCOLOR_WINDOWS_DESKTOP", SysColor::SYSCOLOR_WINDOWS_DESKTOP)
      .value("eSYSCOLOR_WINDOWS_APPWORKSPACE", SysColor::SYSCOLOR_WINDOWS_APPWORKSPACE)
      .value("eSYSCOLOR_WINDOWS_TITLEBAR", SysColor::SYSCOLOR_WINDOWS_TITLEBAR)
      .value("eSYSCOLOR_WINDOWS_ITITLEBAR", SysColor::SYSCOLOR_WINDOWS_ITITLEBAR)
      .value("eSYSCOLOR_WINDOWS_TITLEBARTEXT", SysColor::SYSCOLOR_WINDOWS_TITLEBARTEXT)
      .value("eSYSCOLOR_WINDOWS_ITITLEBARTEXT", SysColor::SYSCOLOR_WINDOWS_ITITLEBARTEXT)
      .value("eSYSCOLOR_WINDOWS_BORDER", SysColor::SYSCOLOR_WINDOWS_BORDER)
      .value("eSYSCOLOR_WINDOWS_IBORDER", SysColor::SYSCOLOR_WINDOWS_IBORDER)
      .value("eSYSCOLOR_WINDOWS_DLOGBACKGROUND", SysColor::SYSCOLOR_WINDOWS_DLOGBACKGROUND)
      .value("eSYSCOLOR_WINDOWS_TOOLTIPBG", SysColor::SYSCOLOR_WINDOWS_TOOLTIPBG)
      .value("eSYSCOLOR_WINDOWS_TOOLTIPTEXT", SysColor::SYSCOLOR_WINDOWS_TOOLTIPTEXT)
      .value("eSYSCOLOR_WINDOWS_LIGHT", SysColor::SYSCOLOR_WINDOWS_LIGHT)
      .value("eSYSCOLOR_WINDOWS_DARKSHADOW", SysColor::SYSCOLOR_WINDOWS_DARKSHADOW)
      .value("eSYSCOLOR_WINDOWS_GRADIENTTITLEBAR", SysColor::SYSCOLOR_WINDOWS_GRADIENTTITLEBAR)
      .value("eSYSCOLOR_WINDOWS_GRADIENTITITLEBAR", SysColor::SYSCOLOR_WINDOWS_GRADIENTITITLEBAR)
      .value("eSYSCOLOR_WINDOWS_MENUBAR", SysColor::SYSCOLOR_WINDOWS_MENUBAR)
      .value("eSYSCOLOR_WINDOWS_MENUHILIGHT", SysColor::SYSCOLOR_WINDOWS_MENUHILIGHT)
      .value("eSYSCOLOR_WINDOWS_TOOLBARAREABG", SysColor::SYSCOLOR_WINDOWS_TOOLBARAREABG)
      .value("eSYSCOLOR_WINDOWS_DIALOGAREABG", SysColor::SYSCOLOR_WINDOWS_DIALOGAREABG)
      .value("eSYSCOLOR_WINDOWS_STATUSBAR", SysColor::SYSCOLOR_WINDOWS_STATUSBAR)
      .value("eSYSCOLOR_WINDOWS_RIBBONBG", SysColor::SYSCOLOR_WINDOWS_RIBBONBG)
      .value("eSYSCOLOR_WINDOWS_MAXCOLORS", SysColor::SYSCOLOR_WINDOWS_MAXCOLORS)
      .value("eSYSCOLOR_MAXCOLOR", SysColor::SYSCOLOR_MAXCOLOR)
      .value("eSYSCOLOR_NCOLORS", SysColor::SYSCOLOR_NCOLORS)
      .export_values();

    //===================================================================================
    // enum class ItemColorType
    py::enum_<ItemColorType>(m, "ItemColorType")
      .value("eDITEM_COLORTYPE_BACKGROUND", ItemColorType::DITEM_COLORTYPE_BACKGROUND)
      .value("eDITEM_COLORTYPE_FOREGROUND", ItemColorType::DITEM_COLORTYPE_FOREGROUND)
      .value("eDITEM_COLORTYPE_TOPSHADOW", ItemColorType::DITEM_COLORTYPE_TOPSHADOW)
      .value("eDITEM_COLORTYPE_BOTTOMSHADOW", ItemColorType::DITEM_COLORTYPE_BOTTOMSHADOW)
      .value("eDITEM_COLORTYPE_SELECT", ItemColorType::DITEM_COLORTYPE_SELECT)
      .value("eDITEM_COLORTYPE_AUXLABEL", ItemColorType::DITEM_COLORTYPE_AUXLABEL)
      .value("eDITEM_COLORTYPE_SELECTTEXT", ItemColorType::DITEM_COLORTYPE_SELECTTEXT)
      .value("eDITEM_COLORTYPE_GRAYTEXT", ItemColorType::DITEM_COLORTYPE_GRAYTEXT)
      .value("eDITEM_COLORTYPE_FRAME", ItemColorType::DITEM_COLORTYPE_FRAME)
      .value("eDITEM_COLORTYPE_DLOGBACKGROUND", ItemColorType::DITEM_COLORTYPE_DLOGBACKGROUND)
      .value("eDITEM_COLORTYPE_TRAVHIGHLIGHT", ItemColorType::DITEM_COLORTYPE_TRAVHIGHLIGHT)
      .value("eDITEM_COLORTYPE_SCROLLBAR", ItemColorType::DITEM_COLORTYPE_SCROLLBAR)
      .value("eDITEM_COLORTYPE_TOOLTIPBG", ItemColorType::DITEM_COLORTYPE_TOOLTIPBG)
      .value("eDITEM_COLORTYPE_TOOLTIPTEXT", ItemColorType::DITEM_COLORTYPE_TOOLTIPTEXT)
      .value("eDITEM_COLORTYPE_LIGHT", ItemColorType::DITEM_COLORTYPE_LIGHT)
      .value("eDITEM_COLORTYPE_DARKSHADOW", ItemColorType::DITEM_COLORTYPE_DARKSHADOW)
      .value("eDITEM_COLORTYPE_MAXCOLOR", ItemColorType::DITEM_COLORTYPE_MAXCOLOR)
      .value("eDITEM_COLORTYPE_NCOLORS", ItemColorType::DITEM_COLORTYPE_NCOLORS)
      .export_values();
    
    m.attr("eOUTPUTDEVICE_screen") = (int)OUTPUTDEVICE_screen;
    m.attr("eOUTPUTDEVICE_backingStore") = (int)OUTPUTDEVICE_backingStore;
    m.attr("eOUTPUTDEVICE_doubleBuffer") = (int)OUTPUTDEVICE_doubleBuffer;
    m.attr("eOUTPUTDEVICE_max") = (int)OUTPUTDEVICE_max;
  
    //===================================================================================
    // enum class GuiDrawMode
    py::enum_<GuiDrawMode>(m, "GuiDrawMode")
      .value("eXORDRAW", GuiDrawMode::XORDRAW)
      .value("eTEMPERASE", GuiDrawMode::TEMPERASE)
      .value("eSET_ALLOWBGCOLOR", GuiDrawMode::SET_ALLOWBGCOLOR)
      .value("eHILITE_XORDRAW", GuiDrawMode::HILITE_XORDRAW)
      .value("eXORINCLUDEBACKSTORE", GuiDrawMode::XORINCLUDEBACKSTORE)
      .value("eHILITE_XORINCLUDEBACKSTORE", GuiDrawMode::HILITE_XORINCLUDEBACKSTORE)
      .export_values();
    

    m.attr("eRASTMODE_BYTE_V4_COLOR") = (int)RASTMODE_BYTE_V4_COLOR;
    m.attr("eRASTMODE_BYTE_MONO") = (int)RASTMODE_BYTE_MONO;
    m.attr("eRASTMODE_BYTE_FIXEDCOLOR") = (int)RASTMODE_BYTE_FIXEDCOLOR;
    m.attr("eRASTMODE_COLORDESCR") = (int)RASTMODE_COLORDESCR;
    m.attr("eRASTMODE_LONG_DRAWINDEX") = (int)RASTMODE_LONG_DRAWINDEX;
    m.attr("eRASTMODE_BYTE_PALETTE_INDEX") = (int)RASTMODE_BYTE_PALETTE_INDEX;
    m.attr("eRASTMODE_WORD_PALETTE_INDEX") = (int)RASTMODE_WORD_PALETTE_INDEX;
    m.attr("eRASTMODE_LONG_PALETTE_INDEX") = (int)RASTMODE_LONG_PALETTE_INDEX;

    m.attr("eTRUECOLOR_Seperate") = (int)TRUECOLOR_Seperate;
    m.attr("eTRUECOLOR_Separate") = (int)TRUECOLOR_Separate;
    m.attr("eTRUECOLOR_RGB") = (int)TRUECOLOR_RGB;
    m.attr("eTRUECOLOR_RGBA") = (int)TRUECOLOR_RGBA;
    
    //===================================================================================
    // enum class MstnCapabilityValues
    py::enum_<MstnCapabilityValues>(m, "MstnCapabilityValues")
      .value("eCAPABILITY_ELEMENT_ASSOCIATION", MstnCapabilityValues::CAPABILITY_ELEMENT_ASSOCIATION)
      .value("eCAPABILITY_ELEMENT_LOCK", MstnCapabilityValues::CAPABILITY_ELEMENT_LOCK)
      .value("eCAPABILITY_ELEMENT_CLASS", MstnCapabilityValues::CAPABILITY_ELEMENT_CLASS)
      .value("eCAPABILITY_ELEMENT_TRANSPARENCY", MstnCapabilityValues::CAPABILITY_ELEMENT_TRANSPARENCY)
      .value("eCAPABILITY_ELEMENT_PRIORITY", MstnCapabilityValues::CAPABILITY_ELEMENT_PRIORITY)
      .value("eCAPABILITY_BYCELL", MstnCapabilityValues::CAPABILITY_BYCELL)
      .value("eCAPABILITY_BYLEVEL", MstnCapabilityValues::CAPABILITY_BYLEVEL)
      .value("eCAPABILITY_ELEMENT_VIEWINDEPENDENT", MstnCapabilityValues::CAPABILITY_ELEMENT_VIEWINDEPENDENT)
      .value("eCAPABILITY_TYPE2_CELL", MstnCapabilityValues::CAPABILITY_TYPE2_CELL)
      .value("eCAPABILITY_SHAREDCELLS_FROM_ATTACHED_LIB", MstnCapabilityValues::CAPABILITY_SHAREDCELLS_FROM_ATTACHED_LIB)
      .value("eCAPABILITY_SHAREDCELLS_FROM_REFERENCES", MstnCapabilityValues::CAPABILITY_SHAREDCELLS_FROM_REFERENCES)
      .value("eCAPABILITY_DGN_BLOCKS", MstnCapabilityValues::CAPABILITY_DGN_BLOCKS)
      .value("eCAPABILITY_CELLLIB_ALLOWUPGRADEV7", MstnCapabilityValues::CAPABILITY_CELLLIB_ALLOWUPGRADEV7)
      .value("eCAPABILITY_CELLS_ATTRIBUTE_CHANGES", MstnCapabilityValues::CAPABILITY_CELLS_ATTRIBUTE_CHANGES)
      .value("eCAPABILITY_MASK_CLIP", MstnCapabilityValues::CAPABILITY_MASK_CLIP)
      .value("eCAPABILITY_SELF_REFERENCE", MstnCapabilityValues::CAPABILITY_SELF_REFERENCE)
      .value("eCAPABILITY_REF_SCALELINESTYLE", MstnCapabilityValues::CAPABILITY_REF_SCALELINESTYLE)
      .value("eCAPABILITY_REF_AUX_INFO", MstnCapabilityValues::CAPABILITY_REF_AUX_INFO)
      .value("eCAPABILITY_REF_FROM_URL", MstnCapabilityValues::CAPABILITY_REF_FROM_URL)
      .value("eCAPABILITY_REF_DISP_PER_VIEW", MstnCapabilityValues::CAPABILITY_REF_DISP_PER_VIEW)
      .value("eCAPABILITY_REF_SAVE_PATH_REL", MstnCapabilityValues::CAPABILITY_REF_SAVE_PATH_REL)
      .value("eCAPABILITY_REF_RASTERDISPLAY_OFF", MstnCapabilityValues::CAPABILITY_REF_RASTERDISPLAY_OFF)
      .value("eCAPABILITY_REF_ADJUSTCOLORS", MstnCapabilityValues::CAPABILITY_REF_ADJUSTCOLORS)
      .value("eCAPABILITY_REF_NONDEFAULT_MODEL", MstnCapabilityValues::CAPABILITY_REF_NONDEFAULT_MODEL)
      .value("eCAPABILITY_REF_NESTING_OPTIONS", MstnCapabilityValues::CAPABILITY_REF_NESTING_OPTIONS)
      .value("eCAPABILITY_REFERENCE_ATTACHLEVEL", MstnCapabilityValues::CAPABILITY_REFERENCE_ATTACHLEVEL)
      .value("eCAPABILITY_REFERENCE_VIEWLEVELDISPLAY", MstnCapabilityValues::CAPABILITY_REFERENCE_VIEWLEVELDISPLAY)
      .value("eCAPABILITY_REFERENCE_SHEET_LOGICALNAME", MstnCapabilityValues::CAPABILITY_REFERENCE_SHEET_LOGICALNAME)
      .value("eCAPABILITY_REFERENCE_GEOREPROJECT", MstnCapabilityValues::CAPABILITY_REFERENCE_GEOREPROJECT)
      .value("eCAPABILITY_REFERENCE_HIDDENLINE", MstnCapabilityValues::CAPABILITY_REFERENCE_HIDDENLINE)
      .value("eCAPABILITY_REFERENCE_3DTO2D", MstnCapabilityValues::CAPABILITY_REFERENCE_3DTO2D)
      .value("eCAPABILITY_REFERENCE_V8", MstnCapabilityValues::CAPABILITY_REFERENCE_V8)
      .value("eCAPABILITY_REFERENCE_DWG", MstnCapabilityValues::CAPABILITY_REFERENCE_DWG)
      .value("eCAPABILITY_REFERENCE_ALLOW_DXF", MstnCapabilityValues::CAPABILITY_REFERENCE_ALLOW_DXF)
      .value("eCAPABILITY_REFERENCE_LINESTYLESCALE", MstnCapabilityValues::CAPABILITY_REFERENCE_LINESTYLESCALE)
      .value("eCAPABILITY_REFERENCE_TRANSPARENCY", MstnCapabilityValues::CAPABILITY_REFERENCE_TRANSPARENCY)
      .value("eCAPABILITY_REFERENCE_PRIORITY", MstnCapabilityValues::CAPABILITY_REFERENCE_PRIORITY)
      .value("eCAPABILITY_REFERENCE_DISPLAYOVERRIDES", MstnCapabilityValues::CAPABILITY_REFERENCE_DISPLAYOVERRIDES)
      .value("eCAPABILITY_REFERENCE_NEWLEVELDISPLAY", MstnCapabilityValues::CAPABILITY_REFERENCE_NEWLEVELDISPLAY)
      .value("eCAPABILITY_ACTIVATE_REFERENCE_INTERNAL", MstnCapabilityValues::CAPABILITY_ACTIVATE_REFERENCE_INTERNAL)
      .value("eCAPABILITY_ACTIVATE_REFERENCE_EXTERNAL", MstnCapabilityValues::CAPABILITY_ACTIVATE_REFERENCE_EXTERNAL)
      .value("eCAPABILITY_REFERENCE_ANNOTATIONSCALE", MstnCapabilityValues::CAPABILITY_REFERENCE_ANNOTATIONSCALE)
      .value("eCAPABILITY_TYPE90_ALL", MstnCapabilityValues::CAPABILITY_TYPE90_ALL)
      .value("eCAPABILITY_TYPE87_RASTER", MstnCapabilityValues::CAPABILITY_TYPE87_RASTER)
      .value("eCAPABILITY_RASTER_TINT", MstnCapabilityValues::CAPABILITY_RASTER_TINT)
      .value("eCAPABILITY_RASTER_TRANSP_FULL_CONTROL", MstnCapabilityValues::CAPABILITY_RASTER_TRANSP_FULL_CONTROL)
      .value("eCAPABILITY_RASTER_BACKGROUND", MstnCapabilityValues::CAPABILITY_RASTER_BACKGROUND)
      .value("eCAPABILITY_RASTER_PROJECT", MstnCapabilityValues::CAPABILITY_RASTER_PROJECT)
      .value("eCAPABILITY_RASTER_DISP_GAMMA", MstnCapabilityValues::CAPABILITY_RASTER_DISP_GAMMA)
      .value("eCAPABILITY_RASTER_PRINT_GAMMA", MstnCapabilityValues::CAPABILITY_RASTER_PRINT_GAMMA)
      .value("eCAPABILITY_RASTER_PRINT", MstnCapabilityValues::CAPABILITY_RASTER_PRINT)
      .value("eCAPABILITY_RASTER_ALL_TYPES", MstnCapabilityValues::CAPABILITY_RASTER_ALL_TYPES)
      .value("eCAPABILITY_RASTER_INVERT", MstnCapabilityValues::CAPABILITY_RASTER_INVERT)
      .value("eCAPABILITY_RASTER_APPLYROTATIONANDAFFINITY", MstnCapabilityValues::CAPABILITY_RASTER_APPLYROTATIONANDAFFINITY)
      .value("eCAPABILITY_RASTER_GEOREFERENCEPRIORITY", MstnCapabilityValues::CAPABILITY_RASTER_GEOREFERENCEPRIORITY)
      .value("eCAPABILITY_RASTER_PHOTOMATCH", MstnCapabilityValues::CAPABILITY_RASTER_PHOTOMATCH)
      .value("eCAPABILITY_DEFAULT_FONTS", MstnCapabilityValues::CAPABILITY_DEFAULT_FONTS)
      .value("eCAPABILITY_TEXT_FONTS", MstnCapabilityValues::CAPABILITY_TEXT_FONTS)
      .value("eCAPABILITY_TEXT_FONTS_RSC", MstnCapabilityValues::CAPABILITY_TEXT_FONTS_RSC)
      .value("eCAPABILITY_TEXT_FONTS_SHX", MstnCapabilityValues::CAPABILITY_TEXT_FONTS_SHX)
      .value("eCAPABILITY_TEXT_FONTS_TRUETYPE", MstnCapabilityValues::CAPABILITY_TEXT_FONTS_TRUETYPE)
      .value("eCAPABILITY_TEXT_SHXBIGFONTS", MstnCapabilityValues::CAPABILITY_TEXT_SHXBIGFONTS)
      .value("eCAPABILITY_TEXT_HEIGHT", MstnCapabilityValues::CAPABILITY_TEXT_HEIGHT)
      .value("eCAPABILITY_TEXT_WIDTH", MstnCapabilityValues::CAPABILITY_TEXT_WIDTH)
      .value("eCAPABILITY_TEXT_COLOR", MstnCapabilityValues::CAPABILITY_TEXT_COLOR)
      .value("eCAPABILITY_TEXT_JUSTIFICATION", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LT", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LT)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LC", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LC)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LB", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LB)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LMT", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LMT)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LMC", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LMC)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_LMB", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_LMB)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_CT", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_CT)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_CC", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_CC)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_CB", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_CB)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RMT", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RMT)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RMC", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RMC)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RMB", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RMB)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RT", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RT)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RC", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RC)
      .value("eCAPABILITY_TEXT_JUSTIFICATION_RB", MstnCapabilityValues::CAPABILITY_TEXT_JUSTIFICATION_RB)
      .value("eCAPABILITY_TEXT_NODEJUSTIFICATION", MstnCapabilityValues::CAPABILITY_TEXT_NODEJUSTIFICATION)
      .value("eCAPABILITY_TEXT_BOLD", MstnCapabilityValues::CAPABILITY_TEXT_BOLD)
      .value("eCAPABILITY_TEXT_UNDERLINE", MstnCapabilityValues::CAPABILITY_TEXT_UNDERLINE)
      .value("eCAPABILITY_TEXT_UNDERLINE_STYLE", MstnCapabilityValues::CAPABILITY_TEXT_UNDERLINE_STYLE)
      .value("eCAPABILITY_TEXT_UNDERLINE_COLOR", MstnCapabilityValues::CAPABILITY_TEXT_UNDERLINE_COLOR)
      .value("eCAPABILITY_TEXT_UNDERLINE_WEIGHT", MstnCapabilityValues::CAPABILITY_TEXT_UNDERLINE_WEIGHT)
      .value("eCAPABILITY_TEXT_UNDERLINE_OFFSET", MstnCapabilityValues::CAPABILITY_TEXT_UNDERLINE_OFFSET)
      .value("eCAPABILITY_TEXT_OVERLINE", MstnCapabilityValues::CAPABILITY_TEXT_OVERLINE)
      .value("eCAPABILITY_TEXT_OVERLINE_STYLE", MstnCapabilityValues::CAPABILITY_TEXT_OVERLINE_STYLE)
      .value("eCAPABILITY_TEXT_OVERLINE_COLOR", MstnCapabilityValues::CAPABILITY_TEXT_OVERLINE_COLOR)
      .value("eCAPABILITY_TEXT_OVERLINE_WEIGHT", MstnCapabilityValues::CAPABILITY_TEXT_OVERLINE_WEIGHT)
      .value("eCAPABILITY_TEXT_OVERLINE_OFFSET", MstnCapabilityValues::CAPABILITY_TEXT_OVERLINE_OFFSET)
      .value("eCAPABILITY_TEXT_VERTICAL", MstnCapabilityValues::CAPABILITY_TEXT_VERTICAL)
      .value("eCAPABILITY_TEXT_ITALICS", MstnCapabilityValues::CAPABILITY_TEXT_ITALICS)
      .value("eCAPABILITY_TEXT_SLANTANGLE", MstnCapabilityValues::CAPABILITY_TEXT_SLANTANGLE)
      .value("eCAPABILITY_TEXT_BACKGROUND", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND)
      .value("eCAPABILITY_TEXT_BACKGROUND_BORDER_X", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_BORDER_X)
      .value("eCAPABILITY_TEXT_BACKGROUND_BORDER_Y", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_BORDER_Y)
      .value("eCAPABILITY_TEXT_BACKGROUND_COLOR", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_COLOR)
      .value("eCAPABILITY_TEXT_BACKGROUND_FILL_COLOR", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_FILL_COLOR)
      .value("eCAPABILITY_TEXT_BACKGROUND_STYLE", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_STYLE)
      .value("eCAPABILITY_TEXT_BACKGROUND_WEIGHT", MstnCapabilityValues::CAPABILITY_TEXT_BACKGROUND_WEIGHT)
      .value("eCAPABILITY_TEXT_SUPERSCRIPT", MstnCapabilityValues::CAPABILITY_TEXT_SUPERSCRIPT)
      .value("eCAPABILITY_TEXT_SUBSCRIPT", MstnCapabilityValues::CAPABILITY_TEXT_SUBSCRIPT)
      .value("eCAPABILITY_TEXT_LINELENGTH", MstnCapabilityValues::CAPABILITY_TEXT_LINELENGTH)
      .value("eCAPABILITY_TEXT_LINESPACING", MstnCapabilityValues::CAPABILITY_TEXT_LINESPACING)
      .value("eCAPABILITY_TEXT_LINESPACINGTYPE", MstnCapabilityValues::CAPABILITY_TEXT_LINESPACINGTYPE)
      .value("eCAPABILITY_TEXT_INTERCHARACTERSPACING", MstnCapabilityValues::CAPABILITY_TEXT_INTERCHARACTERSPACING)
      .value("eCAPABILITY_TEXT_FIXEDSPACING", MstnCapabilityValues::CAPABILITY_TEXT_FIXEDSPACING)
      .value("eCAPABILITY_TEXT_FRACTIONS", MstnCapabilityValues::CAPABILITY_TEXT_FRACTIONS)
      .value("eCAPABILITY_TEXT_LINEOFFSET_X", MstnCapabilityValues::CAPABILITY_TEXT_LINEOFFSET_X)
      .value("eCAPABILITY_TEXT_LINEOFFSET_Y", MstnCapabilityValues::CAPABILITY_TEXT_LINEOFFSET_Y)
      .value("eCAPABILITY_TEXT_FULLJUSTIFICATION", MstnCapabilityValues::CAPABILITY_TEXT_FULLJUSTIFICATION)
      .value("eCAPABILITY_TEXT_BACKWARDS", MstnCapabilityValues::CAPABILITY_TEXT_BACKWARDS)
      .value("eCAPABILITY_TEXT_UPSIDEDOWN", MstnCapabilityValues::CAPABILITY_TEXT_UPSIDEDOWN)
      .value("eCAPABILITY_TEXT_AUTOSTACKFRACTIONS", MstnCapabilityValues::CAPABILITY_TEXT_AUTOSTACKFRACTIONS)
      .value("eCAPABILITY_TEXT_TTF_VERTICAL", MstnCapabilityValues::CAPABILITY_TEXT_TTF_VERTICAL)
      .value("eCAPABILITY_PLACETEXT_DISPLAY_TOGGLES", MstnCapabilityValues::CAPABILITY_PLACETEXT_DISPLAY_TOGGLES)
      .value("eCAPABILITY_TEXTSTYLE_ACTIVE_DGNSETTINGS", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_ACTIVE_DGNSETTINGS)
      .value("eCAPABILITY_TEXTSTYLE_ACTIVE_DWGSETTINGS", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_ACTIVE_DWGSETTINGS)
      .value("eCAPABILITY_TEXTSTYLE_STYLE_DGNSETTINGS", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_STYLE_DGNSETTINGS)
      .value("eCAPABILITY_TEXTSTYLE_STYLE_DWGSETTINGS", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_STYLE_DWGSETTINGS)
      .value("eCAPABILITY_TEXTSTYLE_ALLOW_CREATE", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_ALLOW_CREATE)
      .value("eCAPABILITY_TEXTSTYLE_ALLOW_DELETE", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_ALLOW_DELETE)
      .value("eCAPABILITY_TEXTSTYLE_ALLOW_MODIFY", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_ALLOW_MODIFY)
      .value("eCAPABILITY_TEXTSTYLE_NOSTYLE", MstnCapabilityValues::CAPABILITY_TEXTSTYLE_NOSTYLE)
      .value("eCAPABILITY_WORDPROCESSOR_USE_RSCFRACTIONS", MstnCapabilityValues::CAPABILITY_WORDPROCESSOR_USE_RSCFRACTIONS)
      .value("eCAPABILITY_WORDPROC_FIELD_MODELPROPERTIES", MstnCapabilityValues::CAPABILITY_WORDPROC_FIELD_MODELPROPERTIES)
      .value("eCAPABILITY_WORDPROC_FIELD_SIGNATUREPLACEHOLDER", MstnCapabilityValues::CAPABILITY_WORDPROC_FIELD_SIGNATUREPLACEHOLDER)
      .value("eCAPABILITY_WORDPROC_FIELD_LINKPLACEHOLDER", MstnCapabilityValues::CAPABILITY_WORDPROC_FIELD_LINKPLACEHOLDER)
      .value("eCAPABILITY_WORDPROC_FIELD_CELLPLACEHOLDER", MstnCapabilityValues::CAPABILITY_WORDPROC_FIELD_CELLPLACEHOLDER)
      .value("eCAPABILITY_WORDPROC_FIELD_PRINTPROPERTIES", MstnCapabilityValues::CAPABILITY_WORDPROC_FIELD_PRINTPROPERTIES)
      .value("eCAPABILITY_TAGS_COPY_WITH_BASE", MstnCapabilityValues::CAPABILITY_TAGS_COPY_WITH_BASE)
      .value("eCAPABILITY_TAG_NOCELL_ELEMS", MstnCapabilityValues::CAPABILITY_TAG_NOCELL_ELEMS)
      .value("eCAPABILITY_IGDS_LINESTYLE", MstnCapabilityValues::CAPABILITY_IGDS_LINESTYLE)
      .value("eCAPABILITY_CREATE_POINT_STYLE", MstnCapabilityValues::CAPABILITY_CREATE_POINT_STYLE)
      .value("eCAPABILITY_CREATE_COMPOUND_STYLE", MstnCapabilityValues::CAPABILITY_CREATE_COMPOUND_STYLE)
      .value("eCAPABILITY_DWGINCOMPATIBLE_LINESTYLES", MstnCapabilityValues::CAPABILITY_DWGINCOMPATIBLE_LINESTYLES)
      .value("eCAPABILITY_ALLOW_NON_SHX_STYLES", MstnCapabilityValues::CAPABILITY_ALLOW_NON_SHX_STYLES)
      .value("eCAPABILITY_LINESTYLE_SCALEDWIDTH", MstnCapabilityValues::CAPABILITY_LINESTYLE_SCALEDWIDTH)
      .value("eCAPABILITY_LINESTYLE_CREATE_STDTXT", MstnCapabilityValues::CAPABILITY_LINESTYLE_CREATE_STDTXT)
      .value("eCAPABILITY_LINESTYLE_CREATE_TEXTSTYLE", MstnCapabilityValues::CAPABILITY_LINESTYLE_CREATE_TEXTSTYLE)
      .value("eCAPABILITY_LINESTYLE_SCALE_PER_MODEL", MstnCapabilityValues::CAPABILITY_LINESTYLE_SCALE_PER_MODEL)
      .value("eCAPABILITY_DIMENSION_NOSTYLE", MstnCapabilityValues::CAPABILITY_DIMENSION_NOSTYLE)
      .value("eCAPABILITY_DIMENSION_CUSTOM_PREFIX", MstnCapabilityValues::CAPABILITY_DIMENSION_CUSTOM_PREFIX)
      .value("eCAPABILITY_DIMENSION_DIMLINE_LEVEL", MstnCapabilityValues::CAPABILITY_DIMENSION_DIMLINE_LEVEL)
      .value("eCAPABILITY_DIMENSION_ARBITARY", MstnCapabilityValues::CAPABILITY_DIMENSION_ARBITARY)
      .value("eCAPABILITY_DIMENSION_TERM_ATTRIBS", MstnCapabilityValues::CAPABILITY_DIMENSION_TERM_ATTRIBS)
      .value("eCAPABILITY_DIMENSION_TERM_SYMBOL", MstnCapabilityValues::CAPABILITY_DIMENSION_TERM_SYMBOL)
      .value("eCAPABILITY_DIMENSION_TERM_FIRST", MstnCapabilityValues::CAPABILITY_DIMENSION_TERM_FIRST)
      .value("eCAPABILITY_DIMENSION_TERM_JOINT", MstnCapabilityValues::CAPABILITY_DIMENSION_TERM_JOINT)
      .value("eCAPABILITY_DIMENSION_WORKING_UNITS", MstnCapabilityValues::CAPABILITY_DIMENSION_WORKING_UNITS)
      .value("eCAPABILITY_DIMENSION_METRIC_FORMAT", MstnCapabilityValues::CAPABILITY_DIMENSION_METRIC_FORMAT)
      .value("eCAPABILITY_DIMENSION_SECONDARY_ZEROS", MstnCapabilityValues::CAPABILITY_DIMENSION_SECONDARY_ZEROS)
      .value("eCAPABILITY_DIMENSION_ALT_LABEL", MstnCapabilityValues::CAPABILITY_DIMENSION_ALT_LABEL)
      .value("eCAPABILITY_DIMENSION_ARC_ABOVE", MstnCapabilityValues::CAPABILITY_DIMENSION_ARC_ABOVE)
      .value("eCAPABILITY_DIMENSION_ARC_LENGTH", MstnCapabilityValues::CAPABILITY_DIMENSION_ARC_LENGTH)
      .value("eCAPABILITY_DIMENSION_CELLTERM_HEIGHT", MstnCapabilityValues::CAPABILITY_DIMENSION_CELLTERM_HEIGHT)
      .value("eCAPABILITY_DIMENSION_UNDERLINE_TEXT", MstnCapabilityValues::CAPABILITY_DIMENSION_UNDERLINE_TEXT)
      .value("eCAPABILITY_DIMENSION_BALLNCHAIN", MstnCapabilityValues::CAPABILITY_DIMENSION_BALLNCHAIN)
      .value("eCAPABILITY_DIMENSION_UNIT_LABEL", MstnCapabilityValues::CAPABILITY_DIMENSION_UNIT_LABEL)
      .value("eCAPABILITY_DIMENSION_UNIT_FORMAT", MstnCapabilityValues::CAPABILITY_DIMENSION_UNIT_FORMAT)
      .value("eCAPABILITY_DIMENSION_TEXT_WEIGHT", MstnCapabilityValues::CAPABILITY_DIMENSION_TEXT_WEIGHT)
      .value("eCAPABILITY_DIMENSION_LSTYLE_OVERRIDE", MstnCapabilityValues::CAPABILITY_DIMENSION_LSTYLE_OVERRIDE)
      .value("eCAPABILITY_DIMENSION_CAPSULE_FRAME", MstnCapabilityValues::CAPABILITY_DIMENSION_CAPSULE_FRAME)
      .value("eCAPABILITY_DIMENSION_CUSTOM_SYMBOLS", MstnCapabilityValues::CAPABILITY_DIMENSION_CUSTOM_SYMBOLS)
      .value("eCAPABILITY_DIMENSION_TEXT_MARGIN", MstnCapabilityValues::CAPABILITY_DIMENSION_TEXT_MARGIN)
      .value("eCAPABILITY_DIMENSION_MINIMUM_LEADER", MstnCapabilityValues::CAPABILITY_DIMENSION_MINIMUM_LEADER)
      .value("eCAPABILITY_DIMENSION_FONT", MstnCapabilityValues::CAPABILITY_DIMENSION_FONT)
      .value("eCAPABILITY_DIMENSION_TEXT_WIDTH", MstnCapabilityValues::CAPABILITY_DIMENSION_TEXT_WIDTH)
      .value("eCAPABILITY_DIMENSION_NEG_EXTOFFSET", MstnCapabilityValues::CAPABILITY_DIMENSION_NEG_EXTOFFSET)
      .value("eCAPABILITY_DIMENSION_TEXT_HEIGHT_SCALE", MstnCapabilityValues::CAPABILITY_DIMENSION_TEXT_HEIGHT_SCALE)
      .value("eCAPABILITY_DIMENSION_TERM_SIDES", MstnCapabilityValues::CAPABILITY_DIMENSION_TERM_SIDES)
      .value("eCAPABILITY_DIMENSION_USE_MINLEADER", MstnCapabilityValues::CAPABILITY_DIMENSION_USE_MINLEADER)
      .value("eCAPABILITY_DIMENSION_TEXT_JUSTIFICATION", MstnCapabilityValues::CAPABILITY_DIMENSION_TEXT_JUSTIFICATION)
      .value("eCAPABILITY_DIMENSION_WIDEFIT_TEXTABOVE", MstnCapabilityValues::CAPABILITY_DIMENSION_WIDEFIT_TEXTABOVE)
      .value("eCAPABILITY_DIMENSION_INCLINED_FIT", MstnCapabilityValues::CAPABILITY_DIMENSION_INCLINED_FIT)
      .value("eCAPABILITY_DIMENSION_FRACTION_SCALE", MstnCapabilityValues::CAPABILITY_DIMENSION_FRACTION_SCALE)
      .value("eCAPABILITY_DIMENSION_DIN", MstnCapabilityValues::CAPABILITY_DIMENSION_DIN)
      .value("eCAPABILITY_DIMENSION_TOL_MARGINS", MstnCapabilityValues::CAPABILITY_DIMENSION_TOL_MARGINS)
      .value("eCAPABILITY_NOTE_ELBOWLENGTH", MstnCapabilityValues::CAPABILITY_NOTE_ELBOWLENGTH)
      .value("eCAPABILITY_NOTE_LEFTMARGIN", MstnCapabilityValues::CAPABILITY_NOTE_LEFTMARGIN)
      .value("eCAPABILITY_NOTE_LOWERMARGIN", MstnCapabilityValues::CAPABILITY_NOTE_LOWERMARGIN)
      .value("eCAPABILITY_NOTE_ALL_FRAME_TYPES", MstnCapabilityValues::CAPABILITY_NOTE_ALL_FRAME_TYPES)
      .value("eCAPABILITY_NOTE_MANUALATTACHMENT", MstnCapabilityValues::CAPABILITY_NOTE_MANUALATTACHMENT)
      .value("eCAPABILITY_NOTE_MANUALJUSTIFICATION", MstnCapabilityValues::CAPABILITY_NOTE_MANUALJUSTIFICATION)
      .value("eCAPABILITY_NOTE_FRAME_SCALE", MstnCapabilityValues::CAPABILITY_NOTE_FRAME_SCALE)
      .value("eCAPABILITY_DIMSTYLE_REQUIRESTANDARD", MstnCapabilityValues::CAPABILITY_DIMSTYLE_REQUIRESTANDARD)
      .value("eCAPABILITY_DIMENSION_ORDDIM_DATUM", MstnCapabilityValues::CAPABILITY_DIMENSION_ORDDIM_DATUM)
      .value("eCAPABILITY_MODEL_CREATE_DESIGN", MstnCapabilityValues::CAPABILITY_MODEL_CREATE_DESIGN)
      .value("eCAPABILITY_MODEL_CREATE_SHEET", MstnCapabilityValues::CAPABILITY_MODEL_CREATE_SHEET)
      .value("eCAPABILITY_MODEL_WITHOUT_VIEWGROUP", MstnCapabilityValues::CAPABILITY_MODEL_WITHOUT_VIEWGROUP)
      .value("eCAPABILITY_MODEL_CREATE_2D", MstnCapabilityValues::CAPABILITY_MODEL_CREATE_2D)
      .value("eCAPABILITY_MODEL_CREATE_3D", MstnCapabilityValues::CAPABILITY_MODEL_CREATE_3D)
      .value("eCAPABILITY_MODEL_CHANGE_TYPE", MstnCapabilityValues::CAPABILITY_MODEL_CHANGE_TYPE)
      .value("eCAPABILITY_MODEL_DELETE_DESIGN", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_DESIGN)
      .value("eCAPABILITY_MODEL_DELETE_SHEET", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_SHEET)
      .value("eCAPABILITY_MODEL_DELETE_LAST_DESIGN", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_LAST_DESIGN)
      .value("eCAPABILITY_MODEL_DELETE_LAST_SHEET", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_LAST_SHEET)
      .value("eCAPABILITY_MODEL_EDIT_PROPERTIES_DESIGN", MstnCapabilityValues::CAPABILITY_MODEL_EDIT_PROPERTIES_DESIGN)
      .value("eCAPABILITY_MODEL_EDIT_PROPERTIES_SHEET", MstnCapabilityValues::CAPABILITY_MODEL_EDIT_PROPERTIES_SHEET)
      .value("eCAPABILITY_NONDEFAULTMODEL_ANNOTATION_SCALE", MstnCapabilityValues::CAPABILITY_NONDEFAULTMODEL_ANNOTATION_SCALE)
      .value("eCAPABILITY_NONDEFAULTMODEL_ANNOTATION_SCALE_LOCK", MstnCapabilityValues::CAPABILITY_NONDEFAULTMODEL_ANNOTATION_SCALE_LOCK)
      .value("eCAPABILITY_MODEL_DISPLAY_SHEETLAYOUT", MstnCapabilityValues::CAPABILITY_MODEL_DISPLAY_SHEETLAYOUT)
      .value("eCAPABILITY_MODEL_PLACE_AS_CELL", MstnCapabilityValues::CAPABILITY_MODEL_PLACE_AS_CELL)
      .value("eCAPABILITY_MODEL_UNITS_IN_SHEET", MstnCapabilityValues::CAPABILITY_MODEL_UNITS_IN_SHEET)
      .value("eCAPABILITY_MODEL_CREATE_DRAWING", MstnCapabilityValues::CAPABILITY_MODEL_CREATE_DRAWING)
      .value("eCAPABILITY_MODEL_DELETE_DRAWING", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_DRAWING)
      .value("eCAPABILITY_MODEL_DELETE_LAST_DRAWING", MstnCapabilityValues::CAPABILITY_MODEL_DELETE_LAST_DRAWING)
      .value("eCAPABILITY_MODEL_EDIT_PROPERTIES_DRAWING", MstnCapabilityValues::CAPABILITY_MODEL_EDIT_PROPERTIES_DRAWING)
      .value("eCAPABILITY_MODEL_LINESTYLE_SCALE_OPTIONS", MstnCapabilityValues::CAPABILITY_MODEL_LINESTYLE_SCALE_OPTIONS)
      .value("eCAPABILITY_MODEL_SHEET_INDEXING", MstnCapabilityValues::CAPABILITY_MODEL_SHEET_INDEXING)
      .value("eCAPABILITY_VIEWGROUP_CREATION", MstnCapabilityValues::CAPABILITY_VIEWGROUP_CREATION)
      .value("eCAPABILITY_VIEWGROUP_DELETION", MstnCapabilityValues::CAPABILITY_VIEWGROUP_DELETION)
      .value("eCAPABILITY_VIEWGROUP_UPDATE", MstnCapabilityValues::CAPABILITY_VIEWGROUP_UPDATE)
      .value("eCAPABILITY_VIEW_ROTATE_SHEET_MODEL_VIEW", MstnCapabilityValues::CAPABILITY_VIEW_ROTATE_SHEET_MODEL_VIEW)
      .value("eCAPABILITY_VIEW_CLIP", MstnCapabilityValues::CAPABILITY_VIEW_CLIP)
      .value("eCAPABILITY_SAVEDVIEWS_CREATE_FOR_SHEETS", MstnCapabilityValues::CAPABILITY_SAVEDVIEWS_CREATE_FOR_SHEETS)
      .value("eCAPABILITY_SAVEDVIEWS_APPLY_TO_SHEETS", MstnCapabilityValues::CAPABILITY_SAVEDVIEWS_APPLY_TO_SHEETS)
      .value("eCAPABILITY_SAVEDVIEWS_DELETE_FOR_SHEETS", MstnCapabilityValues::CAPABILITY_SAVEDVIEWS_DELETE_FOR_SHEETS)
      .value("eCAPABILITY_SAVEDVIEWS_PROPS_FOR_SHEETS", MstnCapabilityValues::CAPABILITY_SAVEDVIEWS_PROPS_FOR_SHEETS)
      .value("eCAPABILITY_SAVEDVIEWS_UPDATE_FOR_SHEETS", MstnCapabilityValues::CAPABILITY_SAVEDVIEWS_UPDATE_FOR_SHEETS)
      .value("eCAPABILITY_VIEWATTRIBUTES", MstnCapabilityValues::CAPABILITY_VIEWATTRIBUTES)
      .value("eCAPABILITY_MULTILINE_NOSTYLE", MstnCapabilityValues::CAPABILITY_MULTILINE_NOSTYLE)
      .value("eCAPABILITY_MULTILINE_REQUIRESTANDARDSTYLE", MstnCapabilityValues::CAPABILITY_MULTILINE_REQUIRESTANDARDSTYLE)
      .value("eCAPABILITY_MULTILINE_ALLOW_ACTIVE", MstnCapabilityValues::CAPABILITY_MULTILINE_ALLOW_ACTIVE)
      .value("eCAPABILITY_MULTILINE_LINESTYLEMODS", MstnCapabilityValues::CAPABILITY_MULTILINE_LINESTYLEMODS)
      .value("eCAPABILITY_MULTILINE_CAPSYMBOLOGY", MstnCapabilityValues::CAPABILITY_MULTILINE_CAPSYMBOLOGY)
      .value("eCAPABILITY_MULTILINE_WEIGHTS", MstnCapabilityValues::CAPABILITY_MULTILINE_WEIGHTS)
      .value("eCAPABILITY_MULTILINE_CLASS", MstnCapabilityValues::CAPABILITY_MULTILINE_CLASS)
      .value("eCAPABILITY_LEVELS_GLOBALDISPLAY", MstnCapabilityValues::CAPABILITY_LEVELS_GLOBALDISPLAY)
      .value("eCAPABILITY_LEVELS_GLOBALFREEZE", MstnCapabilityValues::CAPABILITY_LEVELS_GLOBALFREEZE)
      .value("eCAPABILITY_LEVELS_NUMBERS", MstnCapabilityValues::CAPABILITY_LEVELS_NUMBERS)
      .value("eCAPABILITY_LEVELS_DESCRIPTION", MstnCapabilityValues::CAPABILITY_LEVELS_DESCRIPTION)
      .value("eCAPABILITY_LEVELS_VPFREEZE", MstnCapabilityValues::CAPABILITY_LEVELS_VPFREEZE)
      .value("eCAPABILITY_LEVELS_OVERRIDES_PER_LEVEL", MstnCapabilityValues::CAPABILITY_LEVELS_OVERRIDES_PER_LEVEL)
      .value("eCAPABILITY_LEVELS_OVERRIDE_SYMBOLOGY", MstnCapabilityValues::CAPABILITY_LEVELS_OVERRIDE_SYMBOLOGY)
      .value("eCAPABILITY_LEVEL_LIBRARY_ATTACH", MstnCapabilityValues::CAPABILITY_LEVEL_LIBRARY_ATTACH)
      .value("eCAPABILITY_LEVEL_LIBRARY_DETACH", MstnCapabilityValues::CAPABILITY_LEVEL_LIBRARY_DETACH)
      .value("eCAPABILITY_LEVELS_CREATE", MstnCapabilityValues::CAPABILITY_LEVELS_CREATE)
      .value("eCAPABILITY_LEVELS_ALLOW_DELETE", MstnCapabilityValues::CAPABILITY_LEVELS_ALLOW_DELETE)
      .value("eCAPABILITY_LEVELS_ALLOW_CREATE", MstnCapabilityValues::CAPABILITY_LEVELS_ALLOW_CREATE)
      .value("eCAPABILITY_LEVELS_VIEWDISPLAY", MstnCapabilityValues::CAPABILITY_LEVELS_VIEWDISPLAY)
      .value("eCAPABILITY_LEVELS_PRIORITY", MstnCapabilityValues::CAPABILITY_LEVELS_PRIORITY)
      .value("eCAPABILITY_LEVELS_TRANSPARENCY", MstnCapabilityValues::CAPABILITY_LEVELS_TRANSPARENCY)
      .value("eCAPABILITY_LEVELS_ELEMENT_ACCESS", MstnCapabilityValues::CAPABILITY_LEVELS_ELEMENT_ACCESS)
      .value("eCAPABILITY_LEVELS_MATERIAL", MstnCapabilityValues::CAPABILITY_LEVELS_MATERIAL)
      .value("eCAPABILITY_LEVELS_USE_AUTO_GENERATED_NUMBERS", MstnCapabilityValues::CAPABILITY_LEVELS_USE_AUTO_GENERATED_NUMBERS)
      .value("eCAPABILITY_LEVELS_OVERRIDE_LSTYLE_PROPERTIES", MstnCapabilityValues::CAPABILITY_LEVELS_OVERRIDE_LSTYLE_PROPERTIES)
      .value("eCAPABILITY_LEVEL_ALLOW_LEVELMANAGER", MstnCapabilityValues::CAPABILITY_LEVEL_ALLOW_LEVELMANAGER)
      .value("eCAPABILITY_CUSTOM_KEYPOINTS", MstnCapabilityValues::CAPABILITY_CUSTOM_KEYPOINTS)
      .value("eCAPABILITY_UNITS_DGNFORMAT", MstnCapabilityValues::CAPABILITY_UNITS_DGNFORMAT)
      .value("eCAPABILITY_UNITS_DGNCOORDREADOUT", MstnCapabilityValues::CAPABILITY_UNITS_DGNCOORDREADOUT)
      .value("eCAPABILITY_UNITS_SUB", MstnCapabilityValues::CAPABILITY_UNITS_SUB)
      .value("eCAPABILITY_UNITS_LABEL", MstnCapabilityValues::CAPABILITY_UNITS_LABEL)
      .value("eCAPABILITY_UNITS_SCIENTIFIC_ACCURACY", MstnCapabilityValues::CAPABILITY_UNITS_SCIENTIFIC_ACCURACY)
      .value("eCAPABILITY_DGNLINK_MULTILINKS_PER_ELEM", MstnCapabilityValues::CAPABILITY_DGNLINK_MULTILINKS_PER_ELEM)
      .value("eCAPABILITY_DGNLINK_NONDGN_REGIONLINKS", MstnCapabilityValues::CAPABILITY_DGNLINK_NONDGN_REGIONLINKS)
      .value("eCAPABILITY_DGNLINK_FOLLOW_TOLINKSET", MstnCapabilityValues::CAPABILITY_DGNLINK_FOLLOW_TOLINKSET)
      .value("eCAPABILITY_DGNLINK_FOLLOW_TOCONFIGVAR", MstnCapabilityValues::CAPABILITY_DGNLINK_FOLLOW_TOCONFIGVAR)
      .value("eCAPABILITY_COLORTABLE", MstnCapabilityValues::CAPABILITY_COLORTABLE)
      .value("eCAPABILITY_COLOR_SHOW_INDEXEDTAB", MstnCapabilityValues::CAPABILITY_COLOR_SHOW_INDEXEDTAB)
      .value("eCAPABILITY_COLOR_SHOW_TRUECOLORTAB", MstnCapabilityValues::CAPABILITY_COLOR_SHOW_TRUECOLORTAB)
      .value("eCAPABILITY_COLOR_SHOW_BOOKTAB", MstnCapabilityValues::CAPABILITY_COLOR_SHOW_BOOKTAB)
      .value("eCAPABILITY_COLOR_SHOW_GRADIENTTAB", MstnCapabilityValues::CAPABILITY_COLOR_SHOW_GRADIENTTAB)
      .value("eCAPABILITY_COLOR_MULTI_GRADIENT", MstnCapabilityValues::CAPABILITY_COLOR_MULTI_GRADIENT)
      .value("eCAPABILITY_COLOR_SHOW_BACKGROUND", MstnCapabilityValues::CAPABILITY_COLOR_SHOW_BACKGROUND)
      .value("eCAPABILITY_UI_LOADFROMACTIVEFILE", MstnCapabilityValues::CAPABILITY_UI_LOADFROMACTIVEFILE)
      .value("eCAPABILITY_UI_IGNOREMENUSFROMRSCMODFILE", MstnCapabilityValues::CAPABILITY_UI_IGNOREMENUSFROMRSCMODFILE)
      .value("eCAPABILITY_UI_IGNOREMENUSFROMDGNLIBS", MstnCapabilityValues::CAPABILITY_UI_IGNOREMENUSFROMDGNLIBS)
      .value("eCAPABILITY_ELEMENTTEMPLATE_HONORLEVELLOCK", MstnCapabilityValues::CAPABILITY_ELEMENTTEMPLATE_HONORLEVELLOCK)
      .value("eCAPABILITY_ELEMENTTEMPLATE_HONORELEMENTLOCK", MstnCapabilityValues::CAPABILITY_ELEMENTTEMPLATE_HONORELEMENTLOCK)
      .value("eCAPABILITY_UI_ALWAYSSHOWADMINWORKFLOW", MstnCapabilityValues::CAPABILITY_UI_ALWAYSSHOWADMINWORKFLOW)
      .value("eCAPABILITY_DESIGN_HISTORY", MstnCapabilityValues::CAPABILITY_DESIGN_HISTORY)
      .value("eCAPABILITY_DDDESIGN", MstnCapabilityValues::CAPABILITY_DDDESIGN)
      .value("eCAPABILITY_STANDARDSCHECKER", MstnCapabilityValues::CAPABILITY_STANDARDSCHECKER)
      .value("eCAPABILITY_FILE_PROTECT", MstnCapabilityValues::CAPABILITY_FILE_PROTECT)
      .value("eCAPABILITY_DIGITAL_SIGNATURES", MstnCapabilityValues::CAPABILITY_DIGITAL_SIGNATURES)
      .value("eCAPABILITY_MATERIAL_ASSIGNBYLEVELCOLOR", MstnCapabilityValues::CAPABILITY_MATERIAL_ASSIGNBYLEVELCOLOR)
      .value("eCAPABILITY_LIGHTING_ALLOWLONGLIGHTNAMES", MstnCapabilityValues::CAPABILITY_LIGHTING_ALLOWLONGLIGHTNAMES)
      .value("eCAPABILITY_PARASOLID", MstnCapabilityValues::CAPABILITY_PARASOLID)
      .value("eCAPABILITY_CURVE_IN_CMPLXCH", MstnCapabilityValues::CAPABILITY_CURVE_IN_CMPLXCH)
      .value("eCAPABILITY_BSPLINE_DISPLAY_CONTROL", MstnCapabilityValues::CAPABILITY_BSPLINE_DISPLAY_CONTROL)
      .value("eCAPABILITY_GRAPHIC_GROUP", MstnCapabilityValues::CAPABILITY_GRAPHIC_GROUP)
      .value("eCAPABILITY_NAMED_GROUPS", MstnCapabilityValues::CAPABILITY_NAMED_GROUPS)
      .value("eCAPABILITY_CELLPATTERN", MstnCapabilityValues::CAPABILITY_CELLPATTERN)
      .value("eCAPABILITY_DISPLAY_STYLE_EDITING", MstnCapabilityValues::CAPABILITY_DISPLAY_STYLE_EDITING)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_MODIFY", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_MODIFY)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_IMPORT", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_IMPORT)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_NONDWG_LIBRARIES", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_NONDWG_LIBRARIES)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_UNITS", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_UNITS)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_CHANGE_PROPERTY_TYPE", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_CHANGE_PROPERTY_TYPE)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_ARRAYS", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_ARRAYS)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_RENAME_USED_ITEMTYPES", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_RENAME_USED_ITEMTYPES)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_ATTACH_TO_NONCELL", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_ATTACH_TO_NONCELL)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_CREATE_PROPERTY_TYPES", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_CREATE_PROPERTY_TYPES)
      .value("eCAPABILITY_ITEMTYPE_ALLOW_ITEM_NAME", MstnCapabilityValues::CAPABILITY_ITEMTYPE_ALLOW_ITEM_NAME)
      .value("eCAPABILITY_REPORTS_ALLOW_MODIFY", MstnCapabilityValues::CAPABILITY_REPORTS_ALLOW_MODIFY)
      .value("eCAPABILITY_REPORTS_ALLOW_IMPORT", MstnCapabilityValues::CAPABILITY_REPORTS_ALLOW_IMPORT)
      .value("eCAPABILITY_REPORTS_ASSOCIATION", MstnCapabilityValues::CAPABILITY_REPORTS_ASSOCIATION)
      .value("eCAPABILITY_CONSTRAINTS", MstnCapabilityValues::CAPABILITY_CONSTRAINTS)
      .value("eCAPABILITY_DETAILINGSYMBOLS", MstnCapabilityValues::CAPABILITY_DETAILINGSYMBOLS)
      .value("eCAPABILITY_POINTCLOUD", MstnCapabilityValues::CAPABILITY_POINTCLOUD)
      .value("eCAPABILITY_TERRAINMODEL", MstnCapabilityValues::CAPABILITY_TERRAINMODEL)
      .value("eCAPABILITY_SAVEDVIEW", MstnCapabilityValues::CAPABILITY_SAVEDVIEW)
      .value("eCAPABILITY_REALITYMESH", MstnCapabilityValues::CAPABILITY_REALITYMESH)
      .value("eCAPABILITY_PRINT3D", MstnCapabilityValues::CAPABILITY_PRINT3D)
      .value("eCAPABILITY_MODELINGMESH", MstnCapabilityValues::CAPABILITY_MODELINGMESH)
      .value("eCAPABILITY_IMPORTRFA", MstnCapabilityValues::CAPABILITY_IMPORTRFA)
      .value("eCAPABILITY_PICKLIST", MstnCapabilityValues::CAPABILITY_PICKLIST)
      .value("eCAPABILITY_ITEMTYPEIMPORTEXPORT", MstnCapabilityValues::CAPABILITY_ITEMTYPEIMPORTEXPORT)
      .value("eCAPABILITY_COMPONENTMODEL", MstnCapabilityValues::CAPABILITY_COMPONENTMODEL)
      .value("eCAPABILITY_SCALE_AXIS_INDEP", MstnCapabilityValues::CAPABILITY_SCALE_AXIS_INDEP)
      .value("eCAPABILITY_LEVEL_PLOT", MstnCapabilityValues::CAPABILITY_LEVEL_PLOT)
      .value("eCAPABILITY_TABLE_DESCRIPTION", MstnCapabilityValues::CAPABILITY_TABLE_DESCRIPTION)
      .value("eCAPABILITY_GRID_ORIENTATION", MstnCapabilityValues::CAPABILITY_GRID_ORIENTATION)
      .value("eCAPABILITY_INVISGEOM_BYELEMENT", MstnCapabilityValues::CAPABILITY_INVISGEOM_BYELEMENT)
      .value("eCAPABILITY_MODIFY_SELECTSERVER", MstnCapabilityValues::CAPABILITY_MODIFY_SELECTSERVER)
      .value("eCAPABILITY_FENCE_NAME", MstnCapabilityValues::CAPABILITY_FENCE_NAME)
      .value("eCAPABILITY_LARGE_DESIGN_PLANE", MstnCapabilityValues::CAPABILITY_LARGE_DESIGN_PLANE)
      .value("eCAPABILITY_TEXT_INSERTSTACKFRACTIONS", MstnCapabilityValues::CAPABILITY_TEXT_INSERTSTACKFRACTIONS)
      .value("eMAX_CAPABILITIES", MstnCapabilityValues::MAX_CAPABILITIES)
      .export_values();

      //===================================================================================
      // enum class AngularUnits
    py::enum_<AngularUnits>(m, "AngularUnits")
      .value("eANGULAR_UNITS_DecimalDegrees", AngularUnits::ANGULAR_UNITS_DecimalDegrees)
      .value("eANGULAR_UNITS_DegreesMinutesSeconds", AngularUnits::ANGULAR_UNITS_DegreesMinutesSeconds)
      .value("eANGULAR_UNITS_Gradians", AngularUnits::ANGULAR_UNITS_Gradians)
      .value("eANGULAR_UNITS_Radians", AngularUnits::ANGULAR_UNITS_Radians)
      .value("eANGULAR_UNITS_Bearing", AngularUnits::ANGULAR_UNITS_Bearing)
      .export_values();

    //===================================================================================
    // enum class CellLibAsyncMsgType
    py::enum_<CellLibAsyncMsgType>(m, "CellLibAsyncMsgType")
      .value("eCELL_LIBRARY_MSG_ERROR", CellLibAsyncMsgType::CELL_LIBRARY_MSG_ERROR)
      .value("eCELL_LIBRARY_PRE_ATTACH", CellLibAsyncMsgType::CELL_LIBRARY_PRE_ATTACH)
      .value("eCELL_LIBRARY_POST_ATTACH", CellLibAsyncMsgType::CELL_LIBRARY_POST_ATTACH)
      .value("eCELL_LIBRARY_PRE_DETACH", CellLibAsyncMsgType::CELL_LIBRARY_PRE_DETACH)
      .value("eCELL_LIBRARY_POST_DETACH", CellLibAsyncMsgType::CELL_LIBRARY_POST_DETACH)
      .value("eCELL_LIBRARY_PRE_CREATE", CellLibAsyncMsgType::CELL_LIBRARY_PRE_CREATE)
      .value("eCELL_LIBRARY_POST_CREATE", CellLibAsyncMsgType::CELL_LIBRARY_POST_CREATE)
      .export_values();
    
    //===================================================================================
    // enum class CellLibraryOptions
    py::enum_<CellLibraryOptions>(m, "CellLibraryOptions")
      .value("eCELL_LIBRARY_OPT_None", CellLibraryOptions::CELL_LIBRARY_OPT_None)
      .value("eCELL_LIBRARY_OPT_Include3d", CellLibraryOptions::CELL_LIBRARY_OPT_Include3d)
      .value("eCELL_LIBRARY_OPT_IncludeAllLibraries", CellLibraryOptions::CELL_LIBRARY_OPT_IncludeAllLibraries)
      .value("eCELL_LIBRARY_OPT_IncludeParametric", CellLibraryOptions::CELL_LIBRARY_OPT_IncludeParametric)
      .value("eCELL_LIBRARY_OPT_IncludeNonParametric", CellLibraryOptions::CELL_LIBRARY_OPT_IncludeNonParametric)
      .value("eCELL_LIBRARY_OPT_IncludeShared", CellLibraryOptions::CELL_LIBRARY_OPT_IncludeShared)
      .export_values();
  

    //===================================================================================
    // enum class TextStyleChangeType
    py::enum_<TextStyleChangeType>(m, "TextStyleChangeType")
      .value("eTEXTSTYLE_CHANGE_ADD", TextStyleChangeType::TEXTSTYLE_CHANGE_ADD)
      .value("eTEXTSTYLE_CHANGE_DELETE", TextStyleChangeType::TEXTSTYLE_CHANGE_DELETE)
      .value("eTEXTSTYLE_CHANGE_MODIFY", TextStyleChangeType::TEXTSTYLE_CHANGE_MODIFY)
      .value("eTEXTSTYLE_CHANGE_DELETEUNUSED", TextStyleChangeType::TEXTSTYLE_CHANGE_DELETEUNUSED)
      .value("eTEXTSTYLE_CHANGE_BEFORE_ADD", TextStyleChangeType::TEXTSTYLE_CHANGE_BEFORE_ADD)
      .value("eTEXTSTYLE_CHANGE_BEFORE_DELETE", TextStyleChangeType::TEXTSTYLE_CHANGE_BEFORE_DELETE)
      .value("eTEXTSTYLE_CHANGE_BEFORE_MODIFY", TextStyleChangeType::TEXTSTYLE_CHANGE_BEFORE_MODIFY)
      .export_values();
    

    //===================================================================================
    // enum class DimensionStyleChangeType
    py::enum_<DimensionStyleChangeType>(m, "DimensionStyleChangeType")
      .value("eDIMSTYLE_TABLE_CHANGE", DimensionStyleChangeType::DIMSTYLE_TABLE_CHANGE)
      .value("eDIMSTYLE_CHANGE_ACTIVE", DimensionStyleChangeType::DIMSTYLE_CHANGE_ACTIVE)
      .value("eDIMSTYLE_CHANGE_PREACTIVE", DimensionStyleChangeType::DIMSTYLE_CHANGE_PREACTIVE)
      .value("eDIMSTYLE_CHANGE_SETTINGS", DimensionStyleChangeType::DIMSTYLE_CHANGE_SETTINGS)
      .export_values();
    }
